### ISSUE TITLE
BMC94360 相关问题

### ISSUE THREAD

**Issue by xz021980** [rangerwill/nuc5i5ryh-hackintosh-efi-catalina-10.15.7#1]
Hi rangerwill,
目前我找到的都要外接 4pin usb2.0，
可以请问您的 BMC94360 是用哪一种转接卡，以及要怎么接呢?

谢谢

**Comment by rangerwill** [comment]
> 
> 
> Hi rangerwill,
> 目前我找到的都要外接 4pin usb2.0，
> 可以请问您的 BMC94360 是用哪一种转接卡，以及要怎么接呢?
> 
> 谢谢

![3228564f3a2eab933ce3c622e8243ae](https://user-images.githubusercontent.com/19543803/101711541-b5a38a80-3ace-11eb-8690-13e988cc1e41.jpg)

这样的转接卡

买Airport、白苹果的拆机卡安装

**Comment by rangerwill** [comment]
> 
> 
> > Hi rangerwill,
> > 目前我找到的都要外接 4pin usb2.0，
> > 可以请问您的 BMC94360 是用哪一种转接卡，以及要怎么接呢?
> > 谢谢
> 
> ![3228564f3a2eab933ce3c622e8243ae](https://user-images.githubusercontent.com/19543803/101711541-b5a38a80-3ace-11eb-8690-13e988cc1e41.jpg)
> 
> 这样的转接卡
> 
> 买Airport、白苹果的拆机卡安装
主板上的针脚数大于转接卡外接针脚数，
所以，
插线的时候，靠USB TypeA接口那一边插。
务必在BIOS中禁用机器内置的蓝牙和WiFi，
否则蓝牙无法使用。
